version: '3.2'

volumes:
  fedora:

services:
  fedora:
    image: nulib/fcrepo4:4.7.5-s3fix
    logging:
      driver: "awslogs"
      options:
        awslogs-group: "${FEDORA_LOGGROUP}"
        awslogs-create-group: "true"
    environment:
      - MODESHAPE_CONFIG=classpath:/config/jdbc-postgresql-s3/repository.json
      - JAVA_OPTIONS=${FEDORA_OPTIONS}
    volumes:
      - fedora:/data
  solr:
    image: avalonmediasystem/solr:latest
    build:
      context: ./solr
      args:
        - AVALON_BRANCH=develop
    volumes:
      - /srv/solr_data:/opt/solr/server/solr/mycores
      - /srv/solr_backups:/backups
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - avalon
      - /opt/solr/avalon_conf
  jobs:
    image: mcuadros/ofelia:latest
    volumes:
      - ./jobs.ini:/etc/ofelia/config.ini
      - /var/run/docker.sock:/var/run/docker.sock
  hls:
    image: avalonmediasystem/nginx:aws
    depends_on:
      - avalon
    build:
      context: ./nginx
    environment:
      - AVALON_STREAMING_BUCKET=${AVALON_STREAMING_BUCKET}
    ports:
       - "8880:80"
  cache:
    image: nginx
    volumes:
      - ./cache.conf:/etc/nginx/conf.d/nginx.conf
    ports:
      - "80:80"
  avalon: &avalon
    image: ${AVALON_DOCKER_REPO}:${AVALON_REV}
    logging:
      driver: "awslogs"
      options:
        awslogs-group: "${AVALON_LOGGROUP}"
        awslogs-create-group: "true"
    build:
      context: ./avalon
      args:
        - AVALON_BRANCH=${AVALON_BRANCH}
        - AVALON_REV=${AVALON_REV}
        - AVALON_REPO=${AVALON_REPO}
        - BASE_URL
    depends_on:
      - fedora
      - solr
    environment:
      - APP_NAME
      - SECRET_KEY_BASE
      - DATABASE_URL=${DATABASE_URL}
      - SETTINGS__EMAIL__MAILER=:aws_sdk
      - SETTINGS__EMAIL__COMMENTS
      - SETTINGS__EMAIL__NOTIFICATION
      - SETTINGS__EMAIL__SUPPORT
      - ENCODE_WORK_DIR=/tmp
      - FEDORA_BASE_PATH
      - FEDORA_NAMESPACE=avalon
      - FEDORA_URL=http://fedoraAdmin:fedoraAdmin@fedora:8080/rest
      - SETTINGS__FFMPEG__PATH=/usr/bin/ffmpeg
      - MASTER_FILE_PATH
      - MASTER_FILE_STRATEGY=delete
      - SETTINGS__MATTERHORN__MEDIA_PATH=/masterfiles
      - MEDIAINFO_PATH=/usr/bin/mediainfo
      - RAILS_ENV=production
      - SETTINGS__REDIS__HOST=${ELASTICACHE_HOST}
      - SETTINGS__REDIS__PORT=6379
      - SMTP_ADDRESS
      - SMTP_AUTHENTICATION
      - SMTP_DOMAIN
      - SMTP_ENABLE_STARTTLS_AUTO
      - SMTP_OPENSSL_VERIFY_MODE
      - SMTP_PASSWORD
      - SMTP_PORT
      - SMTP_USER_NAME
      - SOLR_URL=http://solr:8983/solr/avalon
      - SETTINGS__STREAMING__CONTENT_PATH=/
      - SETTINGS__STREAMING__SERVER=nginx
      - SYSTEM_GROUPS=administrator,group_manager,manager
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - Z3950_ATTRIBUTE
      - Z3950_DATABASE
      - Z3950_HOST
      - Z3950_PORT
  worker:
    <<: *avalon
    command: su -m -c "cd /home/app/avalon && RAILS_ENV=production bundle exec sidekiq -C config/sidekiq.yml" app
