version: '2'

volumes:
  streaming:
  database:
  fedora:
  work:
    
services:
  db:
    image: avalonmediasystem/avalon-5.x:db
    build: ./db
    volumes:
      - database:/data
    environment:
      - AVALON_DB_PASSWORD
      - FEDORA_DB_PASSWORD
      - PGDATA=/data
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
  fedora:
    image: avalonmediasystem/avalon-5.x:fedora
    build: 
      context: ./fedora
      args:
        - FEDORA_DB_PASSWORD
        - FEDORA_VERSION=3.8.1
    depends_on:
      - db
    volumes:
      - fedora:/data
    ports:
      - "8984:8080"
  solr:
    image: avalonmediasystem/avalon-5.x:solr
    build: 
      context: ./solr
      args:
        - AVALON_BRANCH
    ports:
      - "8983:8080"
  matterhorn:
    image: avalonmediasystem/avalon-5.x:matterhorn
    build: 
      context: ./matterhorn
      args:
        - MATTERHORN_VER=1.4
        - MATTERHORN_BRANCH=1.4.x
    volumes:
      - ./masterfiles:/masterfiles
      - streaming:/streamfiles
      - work:/work
    ports:
      - "8080:8080"
  streaming:
    image: avalonmediasystem/avalon-5.x:nginx
    build: 
      context: ./nginx
    volumes:
      - streaming:/data
    ports:
      - "1935:1935"
      - "8880:80"
  avalon:
    image: avalonmediasystem/avalon-5.x:avalon
    build: 
      context: ./avalon
      args:
        - AVALON_BRANCH
    depends_on:
      - db
      - fedora
      - solr
    environment:
      - APP_NAME
      - SECRET_KEY_BASE
      - ASSET_HOST
      - BASE_URL
      - CONTROLLED_VOCABULARY=config/controlled_vocabulary.yml
      - DATABASE_URL=postgres://avalon:${AVALON_DB_PASSWORD}@db/avalon
      - DROPBOX_PATH=/masterfiles/dropbox
      - DROPBOX_URI=./masterfiles/dropbox
      - EMAIL_COMMENTS
      - EMAIL_NOTIFICATION
      - EMAIL_SUPPORT
      - FEDORA_NAMESPACE=avalon
      - FEDORA_URL=http://fedoraAdmin:fedoraAdmin@fedora:8080/fedora
      - FFMPEG_PATH=/usr/bin/ffmpeg
      - MASTER_FILE_PATH
      - MASTER_FILE_STRATEGY=delete
      - MATTERHORN_URL=http://matterhorn_system_account:CHANGE_ME@matterhorn:8080/
      - MEDIAINFO_PATH=/usr/bin/mediainfo
      - RAILS_ENV=production
      - SMTP_ADDRESS
      - SMTP_AUTHENTICATION
      - SMTP_DOMAIN
      - SMTP_ENABLE_STARTTLS_AUTO
      - SMTP_OPENSSL_VERIFY_MODE
      - SMTP_PASSWORD
      - SMTP_PORT
      - SMTP_USER_NAME
      - SOLR_URL=http://solr:8080/solr/avalon
      - STREAM_BASE=/streamfiles
      - STREAM_DEFAULT_QUALITY=medium
      - STREAM_HTTP_BASE=http://${STREAMING_HOST}:8880/avalon
      - STREAM_RTMP_BASE=rtmp://${STREAMING_HOST}/avalon
      - STREAM_SERVER=nginx
      - STREAM_TOKEN_TTL=20
      - SYSTEM_GROUPS=administrator,group_manager,manager
      - Z3950_ATTRIBUTE
      - Z3950_DATABASE
      - Z3950_HOST
      - Z3950_PORT
    volumes:
      - ./masterfiles:/masterfiles
      - ./gems:/gems
    ports:
      - "8888:80"
