version: '2'

volumes:
  streaming:
  database:
  fedora:
  work:
    
services:
  db:
    build: ./db
    volumes:
      - database:/data
    environment:
      - AVALON_DB_PASSWORD
      - FEDORA_DB_PASSWORD
      - PGDATA=/data
      - POSTGRES_USER
  fedora:
    build: 
      context: ./fedora
      args:
        - FEDORA_DB_PASSWORD
        - FEDORA_VERSION
    depends_on:
      - db
    volumes:
      - fedora:/data
  solr:
    build: 
      context: ./solr
      args:
        - AVALON_BRANCH
    ports:
      - "8983:8080"
  matterhorn:
    build: 
      context: ./matterhorn
      args:
        - MATTERHORN_VER
        - MATTERHORN_BRANCH
    volumes:
      - ./masterfiles:/masterfiles
      - streaming:/streamfiles
      - work:/work
  avalon:
    build: 
      context: ./avalon
      args:
        - AVALON_BRANCH
        - DATABASE_URL=postgres://avalon:${AVALON_DB_PASSWORD}@db/avalon
        - SECRET_KEY_BASE
    depends_on:
      - db
      - fedora
      - solr
      - matterhorn
    environment:
      - APP_NAME
      - SECRET_KEY_BASE
      - BASE_URL
      - CONTROLLED_VOCABULARY
      - DATABASE_URL=postgres://avalon:${AVALON_DB_PASSWORD}@db/avalon
      - DROPBOX_PATH
      - DROPBOX_URI
      - EMAIL_COMMENTS
      - EMAIL_NOTIFICATION
      - EMAIL_SUPPORT
      - FEDORA_NAMESPACE
      - FEDORA_URL
      - FFMPEG_PATH
      - MASTER_FILE_PATH
      - MASTER_FILE_STRATEGY
      - MATTERHORN_URL
      - MEDIAINFO_PATH
      - RAILS_ENV
      - SMTP_ADDRESS
      - SMTP_AUTHENTICATION
      - SMTP_DOMAIN
      - SMTP_ENABLE_STARTTLS_AUTO
      - SMTP_OPENSSL_VERIFY_MODE
      - SMTP_PASSWORD
      - SMTP_PORT
      - SMTP_USER_NAME
      - SOLR_URL
      - STREAM_BASE
      - STREAM_DEFAULT_QUALITY
      - STREAM_HTTP_BASE
      - STREAM_RTMP_BASE
      - STREAM_SERVER
      - STREAM_TOKEN_TTL
      - SYSTEM_GROUPS
      - Z3950_ATTRIBUTE
      - Z3950_DATABASE
      - Z3950_HOST
      - Z3950_PORT
    volumes:
      - ./masterfiles:/masterfiles
      - ./gems:/gems
    ports:
      - "8888:80"
  streaming:
    build: 
      context: ./streaming
      args:
        - WOWZA_ADMIN_PASSWORD
        - WOWZA_ADMIN_USER
        - WOWZA_LICENSE_KEY
        - WOWZA_SILENT_INSTALL_KEY
    volumes:
      - streaming:/streamfiles
    ports:
      - "1935:1935"
