---
default: &default
  fedora:
    namespace: avalon
  dropbox:
    path: /masterfiles/dropbox
    upload_uri: scp://localhost/masterfiles/dropbox/
  matterhorn:
    root: http://matterhorn:8080/
    media_path: /masterfiles
    baseApplication: avalon
    cleanup_log: log/cleanup_jobs.log
  mediainfo:
    path: /usr/bin/mediainfo
  email:
    comments: repository@northwestern.edu
    notification: repository@northwestern.edu
    support: repository@northwestern.edu
    mailer:
      smtp:
        address: hostsmtp.northwestern.edu
        port: 25
  streaming:
    server: :wowza
    stream_token_ttl: 20
    content_path: /streamfiles
    rtmp_base: rtmp://streaming/avalon
    http_base: http://streaming:1935/avalon/_definst_
  groups:
    system_groups:
    - administrator
    - manager
    - collection_manager
    - group_manager
  ffmpeg:
    path: /usr/bin/ffmpeg
  controlled_vocabulary:
    path: config/controlled_vocabulary.yml
  master_file_management:
    strategy: 'delete'
  domain:
    host: avalon
development: *default
test: *default
production: *default
